import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { Amplify } from 'aws-amplify'
import { Authenticator } from '@aws-amplify/ui-react'
import '@aws-amplify/ui-react/styles.css'
import outputs from '../amplify_outputs.json'
import './index.css'
import App from './App.jsx'

// Connect the frontend to the Amplify backend (auth + data). `amplify_outputs.json`
// is generated by `npx ampx sandbox` locally and by the Amplify build in production.
Amplify.configure(outputs)

createRoot(document.getElementById('root')).render(
  <StrictMode>
    {/* Authenticator.Provider exposes the current user + sign-out to the whole
        app via the useAuthenticator() hook. It does NOT force login on its own —
        the dictionary stays public; only the Decks tab gates on auth. */}
    <Authenticator.Provider>
      <App />
    </Authenticator.Provider>
  </StrictMode>,
)
